### PR TITLE
Game + colour on the buggy

### PR DESCRIPTION
**Pull request by heidydallard**

### CODE REVIEW

**Comment by jmirabel** [comment]
Sounds nice.
The PythonQt plugin is not able to find numpy. Do you know the issue ?

**Comment by heidydallard** [comment]
Yes I had the same problem but I don't remember now what is the solution.
I think it's something with the path but not sure about it.

**Comment by jmirabel** [comment]
`sys.path` only contains:
```
py> sys.path
['/local/jmirabel/devel/hpp/install/lib/python2.7/site-packages', '/local/jmirabel/devel/hpp/install/lib/python2.7/dist-packages', '/opt/ros/indigo/lib/python2.7/dist-packages', '/home/jmirabel/.python', '', '/usr/lib/python2.7/', '/usr/lib/python2.7/plat-i386-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload']
```

`/usr/local/lib/python2.7/dist-packages/`, at least is missing... Do you know how you fixed it ?

**Comment by heidydallard** [comment]
I guess you have this path in the bash variable ?!

**Comment by jmirabel** [comment]
A (very ugly) work around is to run this before launching the script:
```python
import sys
sys.path.append('/usr/local/lib/python2.7/dist-packages')
sys.path.append('/usr/lib/python2.7/dist-packages')
sys.path.append('/usr/lib/pymodules/python2.7')
```

**Comment by jmirabel** [comment]
I have fixed the issue. The PythonQt module should be initialized without `IgnoreSiteModule` flag.

**Comment by jmirabel** [comment]
Concerning the script:
- it seems the IA is always finding the same solution. Is this normal ? You can use the IDL call `problem.setRandomSeed` if needed.
- I may be doing something wrong but I cannot set the player's camera to a position that suits me. There is an rotation which seems impossible to do... Is there something special to do ?

**Comment by jmirabel** [comment]
And it does not terminate. Do you know the reason ?

**Pull request merged**
